### ISSUE TITLE
install fails, undefined exports: fstWC

### ISSUE THREAD

**Issue by DWFbio** [j-a-thia/genomalicious#2]
Hi, I have been having a problem installing genomalicious (Win7 / R3.6.1).

The error I get is:
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'genomalicious' in namespaceExport(ns, exports):
 undefined exports: fstWC
ERROR: loading failed
* removing 'C:/Users/xxx/Documents/R/win-library/3.6/genomalicious'
Error: Failed to install 'genomalicious' from GitHub:
  (converted from warning) installation of package ‘C:/Users/xxx/AppData/Local/Temp/RtmpeyqBt7/file270c259034fe/genomalicious_0.1.0.tar.gz’ had non-zero exit status

My R skills are limited, so I don't know how to be more specific about the error. Sorry! Any help would be greatly appreciated.

Thanks!

**Comment by j-a-thia** [comment]
Hi Dan,

Thanks for reaching out!

I believe I have fixed the problem: it had to do with updating functions and their names, but forgetting to update the documentation and NAMESPACE. 

I have tested on my own machine, and a colleague has tested it on their own computer, and it should work fine now!

`devtools::install_github('j-a-thia/genomalicious')`

Let me know if you still have problems.

Best,

~ Josh
