### ISSUE TITLE
Error in !"FORMAT" : invalid argument type

### ISSUE THREAD

**Issue by PrestonMcDonald** [j-a-thia/genomalicious#4]
Running vcf2DT on the provided example vcf data_indseq.vcf results in an error at line 135.

**Comment by j-a-thia** [comment]
Hello Preston, thanks for raising the issue.

I know my reply is a bit late, but I actually picked this bug up a few months ago. It should be resolved. 

Any issues, please raise again. I have genomalicious running on the latest version of R.
